# Generated by Django 5.2.8 on 2025-11-27 20:04

import biblioteca.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del autor', max_length=100, validators=[biblioteca.models.validar_nombre_no_vacio])),
                ('nacionalidad', models.CharField(help_text='Nacionalidad del autor', max_length=50)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del libro', max_length=200)),
                ('fecha_publicacion', models.DateField(help_text='Fecha de publicación del libro')),
                ('resumen', models.TextField(help_text='Resumen del libro (mínimo 50 caracteres)', validators=[biblioteca.models.validar_resumen_minimo])),
                ('autor', models.ForeignKey(help_text='Autor del libro', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='biblioteca.autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Texto de la reseña')),
                ('calificacion', models.IntegerField(help_text='Calificación del 1 al 5', validators=[biblioteca.models.validar_calificacion])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de la reseña')),
                ('libro', models.ForeignKey(help_text='Libro al que pertenece la reseña', on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='biblioteca.libro')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha'],
            },
        ),
    ]
