# Generated by Django 5.2.8 on 2025-11-27 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating del 0.0 al 5.0', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
